server:
  port: ${SERVER_PORT:8085}
spring:
  application:
    name: social-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/evolua}
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
springdoc:
  swagger-ui:
    path: /swagger-ui.html
app:
  security:
    jwt:
      secret: ${APP_SECURITY_JWT_SECRET:change-this-secret-before-production-change-this-secret}
