ALTER TABLE check_ins ADD COLUMN IF NOT EXISTS emotion VARCHAR(80);
ALTER TABLE check_ins ADD COLUMN IF NOT EXISTS intensity INTEGER;
ALTER TABLE check_ins ADD COLUMN IF NOT EXISTS energy VARCHAR(24);
ALTER TABLE check_ins ADD COLUMN IF NOT EXISTS context VARCHAR(80);
ALTER TABLE check_ins ADD COLUMN IF NOT EXISTS decision_tags VARCHAR(500);
ALTER TABLE check_ins ADD COLUMN IF NOT EXISTS severity_level VARCHAR(24);
