ALTER TABLE trails
ADD COLUMN IF NOT EXISTS private_trail BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE trails
ADD COLUMN IF NOT EXISTS active_journey BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE trails
ADD COLUMN IF NOT EXISTS generated_by_ai BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE trails
ADD COLUMN IF NOT EXISTS journey_key VARCHAR(120);

ALTER TABLE trails
ADD COLUMN IF NOT EXISTS source_style VARCHAR(120);
